### ISSUE TITLE
Getting asked weird question by beadm

### ISSUE THREAD

**Issue by pentago** [vermaden/beadm#42]
Recently I wated to remove obsolete BE's and got asked this question. I'm not sure why I'm being asked this because it statement is false.

```
odin@asgard ~ % beadm list

BE     Active Mountpoint  Space Created
103    -      -           25.6M 2016-10-11 19:41
103p10 -      -           12.3M 2016-10-11 19:51
11p2   NR     /           17.9G 2016-10-31 23:25


odin@asgard ~ % sudo beadm destroy 103

Are you sure you want to destroy '103'?
This action cannot be undone (y/[n]): y

Boot environment '103' was created from existing snapshot 
Destroy '11p2@2016-10-11-19:51:16' snapshot? (y/[n]): n   <------ What!?

Origin snapshot '11p2@2016-10-11-19:51:16' will be preserved
Destroyed successfully
```

It;s obviously false claim as there's no way old snapshot can be created from the new snapshot. It was created long time before new one. What does this mean? Is this a bug?

**Comment by vermaden** [comment]
Hi,this is desired behaviour, BEADM tries to detect if BE was created with beadm create command (snapshot created just for this purpose) or if BE was created from existing snapshot that MAYBE you want to retain.Sorry for late response.Regards,vermadenOd: "Goran" &lt;notifications@github.com&gt;Do: "vermaden/beadm" &lt;beadm@noreply.github.com&gt;; Wysłane: 10:39 Wtorek 2016-11-29Temat: [vermaden/beadm] Getting asked weird question by beadm (#42)Recently I wated to remove obsolete BE's and got asked this question. I'm not sure why I'm being asked this because it statement is false.
odin@asgard ~ % beadm list

BE     Active Mountpoint  Space Created
103    -      -           25.6M 2016-10-11 19:41
103p10 -      -           12.3M 2016-10-11 19:51
11p2   NR     /           17.9G 2016-10-31 23:25


odin@asgard ~ % sudo beadm destroy 103

Are you sure you want to destroy '103'?
This action cannot be undone (y/[n]): y

Boot environment '103' was created from existing snapshot 
Destroy '11p2@2016-10-11-19:51:16' snapshot? (y/[n]): n   &lt;------ What!?

Origin snapshot '11p2@2016-10-11-19:51:16' will be preserved
Destroyed successfully

It;s obviously false claim as there's no way old snapshot can be created from the new snapshot. It was created long time before new one. What does this mean? Is this a bug?

**Comment by pentago** [comment]
Hi, thanks for reply :)

How come beadm can't understand that BE I'm trying to delete WAS NOT created from existing snapshot, rather much earlier when snapshot it asks about didn't even exist.

To me personally, this isn't much of an issue but it is confusing and someone can mess their things up with it.

**Comment by vermaden** [comment]
I also sometimes 'hit' that issue, but its very rare and harmless (just another question/confirmation) so I did not tracked the issue.

Regards,
vermaden
